

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'


jobs:
deploy:
  - okteto build -t okteto.dev/jack:latest
  - kubectl apply -f k8s/service.yml
  - envsubst < k8s/deployment.yaml | kubectl apply -f -
